### ISSUE TITLE
Is this open source?

### ISSUE THREAD

**Issue by mattes3** [greggman/virtual-webgl#1]
Nice project, indeed!

To be used freely by other people, could you please add a license file with, say, an MIT license? Otherwise, this is your proprietary code that nobody else may legally use.

**Comment by greggman** [comment]
https://github.com/greggman/virtual-webgl/blob/master/src/virtual-webgl.js

**Comment by mattes3** [comment]
Oh, I see! Maybe it would be a good idea to add a LICENSE file to the repo. That way, Github would immediately show the license in the repo header. But: Thanks anyway!
