### ISSUE TITLE
"Illegal invocation" errors on Chrome

### ISSUE THREAD

**Issue by jjhembd** [greggman/virtual-webgl#3]
In Chrome on Windows, I get "Illegal invocation" errors, mostly at this line:
```javascript
  // copy all WebGL constants and functions to the prototype of
  // VirtualWebGLContext
  for (let key in WebGLRenderingContext.prototype) {
    // switch (key) { // ...
        const value = WebGLRenderingContext.prototype[key]; // Illegal invocation
```

It's enough to break the WebGL 2 examples.

**Comment by jjhembd** [comment]
The problem keys are `drawingBufferColorSpace` and `unpackColorSpace`. Skipping these keys in the `switch` statement mostly fixes the WebGL 2 example.
```javascript
      switch (key) {
        case 'canvas':
        case 'drawingBufferWidth':
        case 'drawingBufferHeight':
        case 'drawingBufferColorSpace':
        case 'unpackColorSpace':
          break;
        default: {
          let value;
          try {
            value = WebGL2RenderingContext.prototype[key];
          } catch {
            throw("Couldn't get context key " + key);
          }
```
The "Instanced Drawing & Vertex Array" pane is still not working, perhaps because of another `Illegal invocation` error in twgl related to extensions.

![image](https://user-images.githubusercontent.com/41167620/183669212-7e22f03f-1b34-4dae-bb88-f2a669b035a3.png)

**Comment by greggman** [comment]
thanks for the bug report! 

Updated

https://github.com/greggman/virtual-webgl/commit/66cf2b58e58ccb94963f1fb06e96290363528d62
