### ISSUE TITLE
publish the module to `npm`

### ISSUE THREAD

**Issue by archmoj** [greggman/virtual-webgl#6]
Great library.
It would be great if published to `npm` too.

**Comment by greggman** [comment]
I published the webgl2 one for now: https://www.npmjs.com/package/virtual-webgl

**Comment by archmoj** [comment]
Thanks @greggman. 
Do you have ideas around allowing both versions?
E.g. the entry module could receive an argument to pick the desired version.

**Comment by greggman** [comment]
no, I have no interest in supporting both versions. If you do, feel free to fork it
